# Project 2: Logistic Regresion with Stochastic Gradient Descent
### William Chen
### This project involved implemented logistic regression with stochastic gradient descent on a dataset that tracked various statistics on inidividuals in the United States with the goal of predicting whether they earned in income of over 50,000 dollars or not.

In [1]:
import csv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

#Import data and delete the irrelevant data fields
data = pd.read_csv('income.csv')

del data['fnlwgt']
del data['education']
del data['relationship']
del data['marital']
# del data['capital-gain']
# del data['capital-loss']
del data['native-country']
del data['occupation'] #Too many occupations for one hot encoding?

#Delete all rows that contain "?" in any field and replace income with 1 and 0
data = data.replace('?', np.nan).dropna()
data = data.replace('<=50K', 0)
data = data.replace('>50K', 1)
data.head()

age         workclass  eduwgt   race     sex  capital-gain  capital-loss  \
0   39         State-gov      13  White    Male          2174             0   
1   50  Self-emp-not-inc      13  White    Male             0             0   
2   38           Private       9  White    Male             0             0   
3   53           Private       7  Black    Male             0             0   
4   28           Private      13  Black  Female             0             0   

   hours-per-week  income  
0              40       0  
1              13       0  
2              40       0  
3              40       0  
4              40       0

In [2]:
#One-hot encoding and normalizing where applicable
X = np.column_stack((data['age'].values, data['eduwgt'].values, data['hours-per-week'].values, data['capital-gain'].values, data['capital-loss'].values))
X = (X - np.mean(X))/np.std(X)

# work_OHE = pd.get_dummies(data['workclass'].values, prefix='work')
# race_OHE = pd.get_dummies(data['race'].values, prefix = 'race')
# sex_OHE = pd.get_dummies(data['sex'].values, prefix = 'sex')
# occ_OHE = pd.get_dummies(data['occupation'].values, prefix = 'occupation')

Y = data['income'].values
#X = np.column_stack((X, race_OHE, sex_OHE))

#Divide into training, validation, and test sets
N = len(Y)

tr = int(round(N * 0.8))
val = int(round(N * 0.9))
X_tr = X[0:tr]
Y_tr = Y[0:tr]
X_val = X[tr:val]
Y_val = Y[tr:val]
X_test = X[val:N]
Y_test = Y[val:N]

In [19]:
def predict (x, y, weights):
    yhat = sigmoid(x @ weights)
    for i in yhat:
        if i >= 0.5:
            i = 1
        else:
            i = 0
    acc = (yhat == y).mean()
    return acc

#Followed the Machine Learning in Action textbook for the sigmoid and sgd functions
def sigmoid (inX):
    return 1 / (1 + np.exp(-inX))

def sgd (x, y, lamb, alpha):
    m, n = x.shape
    weights = np.ones(n)
    for i in range(m):
        h = sigmoid(x[i] @ weights)
        error = y[i] - h
        weights = weights - (alpha * error * x[i]) + lamb * weights
        print(weights)
    return weights

In [21]:
lamb = np.linspace(0.0001, 0.01, num = 10)
accuracy_alpha = []
accuracy_lambda = []

weights = sgd(X_tr, Y_tr, 0, 1)

#First, we identify the best learning lambda
# for lam in lamb:
#     weights = sgd(X_tr, Y_tr, lam, 0.01)
#     acc = predict(X_val, Y_val, weights)
#     accuracy_lambda.append(acc)
    
# max_index_lambda = accuracy_lambda.index(max(accuracy_lambda))
# print("A lambda of {} is the most accurate, yielding {}".format(lamb[max_index_lambda], accuracy_lambda[max_index_lambda]))

# weights = sgd(X_tr, Y_tr, 0, 0.01)
# acc = predict(X_test, Y_test, weights)
# print("Test accuracy without L2:", acc)

# weights = sgd(X_tr, Y_tr, lamb[max_index_lambda], 0.01)
# acc = predict(X_test, Y_test, weights)
# print("Test accuracy with L2:", acc)


[0.96318232 0.95878796 0.96335134 1.32402701 0.95659078]
[0.93822083 0.92936126 0.93392463 1.29303145 0.92559522]
[0.91160006 0.89921276 0.90754716 1.26178813 0.89435191]
[0.88660141 0.86857268 0.88095419 1.23028958 0.86285335]
[0.85845066 0.8385767  0.85427964 1.19869438 0.83125816]
[0.83120007 0.80847508 0.82740092 1.16685736 0.79942114]
[0.80535597 0.7771597  0.79745336 1.13492025 0.76748403]
[0.84012219 0.81922411 0.83340765 1.17851218 0.81107596]
[0.84079453 0.81994706 0.83402343 1.13734721 0.81184059]
[0.85308898 0.83390108 0.84643233 0.85572599 0.82653856]
[0.8902133  0.87558493 0.8762952  0.89909855 0.86991111]
[0.92892957 0.91720271 0.91330468 0.94293515 0.91374771]
[0.90007244 0.88711153 0.8853114  0.91123968 0.88205224]
[0.87203129 0.85657603 0.85951515 0.87920758 0.85002014]
[0.90890387 0.89837996 0.89638773 0.92288202 0.89369458]
[0.8812206  0.86696978 0.870071   0.89097492 0.86178748]
[0.85230193 0.83605532 0.84239969 0.85893783 0.8297504 ]
[0.82403045 0.80489179 0.815134

[-16.93125831 -19.00758141 -16.74111607 -78.02541699 -16.76077162]
[-16.99887149 -19.08051292 -16.8051837  -78.10130313 -16.83665776]
[-17.06116619 -19.15344426 -16.86629654 -78.17718908 -16.91254372]
[-17.12641569 -19.22667126 -16.93036419 -78.25307525 -16.98842988]
[-17.18102835 -19.30048895 -16.99443163 -78.32896117 -17.06431581]
[-17.24657338 -19.37371603 -17.05849935 -78.40484742 -17.14020206]
[-17.24657215 -19.37371467 -17.05849816 -78.40484601 -17.14020065]
[-17.30207127 -19.44753247 -17.12256569 -78.48073205 -17.21608668]
[-17.36761636 -19.52075962 -17.18663347 -78.55661836 -17.291973  ]
[-17.43434348 -19.59398695 -17.25661069 -78.63250487 -17.36785951]
[-17.50018415 -19.66721422 -17.32304229 -78.70839132 -17.44374595]
[-17.56720669 -19.74103243 -17.38711019 -78.78427778 -17.51963242]
[-17.63482007 -19.81307777 -17.44674605 -78.86016415 -17.59551879]
[-17.63481902 -19.81307651 -17.44674489 -78.86016282 -17.59551745]
[-17.6348179  -19.81307519 -17.44674379 -78.86016145 -17.59551

c:\users\chenw_za2im\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]



[ -36.39963388  -40.73644571  -35.93310983 -166.92870949  -38.41604383]
[ -36.46281641  -40.80937872  -35.99717877 -167.00459718  -38.49193153]
[ -36.39992935  -40.73733212  -35.93901921 -169.20027472  -38.41604383]
[ -36.46872579  -40.81026512  -36.00397455 -169.27616241  -38.49193153]
[ -36.53634036  -40.88172078  -36.06361146 -169.35205011  -38.56781922]
[ -36.60543227  -40.95465379  -36.12768039 -169.4279378   -38.64370692]
[ -36.67541058  -41.02758679  -36.18879464 -169.5038255   -38.71959461]
[ -36.66447272  -41.01550977  -36.17855018 -169.4911046   -38.80107761]
[ -36.72233681  -41.08873824  -36.24261912 -169.56699229  -38.8769653 ]
[ -36.72233681  -41.08873824  -36.24261912 -169.56699229  -38.8769653 ]
[ -36.65531318  -41.01669164  -36.17855018 -171.64743694  -38.80107761]
[ -36.65531318  -41.01669164  -36.17855018 -171.64743694  -38.80107761]
[ -36.71997306  -41.08962465  -36.24261912 -171.72332463  -38.8769653 ]
[ -36.78640575  -41.16167125  -36.30668806 -171.79921233  -38.9

[ -45.5935342   -51.07471474  -45.01874915 -245.02768809  -49.19744926]
[ -45.6578986   -51.14794321  -45.07543136 -245.10357578  -49.27333696]
[ -45.72019473  -51.21969434  -45.14097764 -245.17946348  -49.34922465]
[ -45.78544554  -51.29292282  -45.20504658 -245.25535117  -49.42511235]
[ -45.85363444  -51.36790585  -45.26614595 -245.3312204   -49.02007522]
[ -45.92331729  -51.44083886  -45.32519192 -245.40710809  -49.09596291]
[ -45.98709076  -51.51318092  -45.38926085 -245.48299579  -49.17185061]
[ -46.04997782  -51.58611393  -45.45332979 -245.55888348  -49.2477383 ]
[ -46.1193652   -51.6593424   -45.51739873 -245.63477118  -49.323626  ]
[ -46.18668429  -51.73227541  -45.57555829 -245.71065887  -49.39951369]
[ -46.25400339  -51.80550388  -45.63962722 -245.78654657  -49.47540139]
[ -46.25400339  -51.80550388  -45.63962722 -245.78654657  -49.47540139]
[ -46.3192542   -51.87695954  -45.70074147 -245.86243426  -49.55128908]
[ -46.38627783  -51.94959708  -45.76244666 -245.93832196  -49.62

[ -58.51893453  -65.53185036  -57.68041243 -417.4463922   -59.4218558 ]
[ -58.51893453  -65.53185036  -57.68041243 -417.4463922   -59.4218558 ]
[ -58.51893445  -65.53185026  -57.68041235 -417.4463921   -59.42185645]
[ -58.5838898   -65.60507874  -57.74448128 -417.5222798   -59.49774415]
[ -58.64677686  -65.67801174  -57.80855022 -417.59816749  -59.57363184]
[ -58.71350502  -65.75124022  -57.8740965  -417.67405519  -59.64951954]
[ -58.71350502  -65.75124022  -57.8740965  -417.67405519  -59.64951954]
[ -58.7743238   -65.82446869  -57.93816544 -417.74994288  -59.72540723]
[ -58.71380049  -65.7524221   -57.88000588 -422.11318058  -59.64951954]
[ -58.77639208  -65.82565057  -57.94407482 -422.18906827  -59.21129128]
[ -58.77639208  -65.82565057  -57.94407482 -422.18906827  -59.21129128]
[ -58.83248335  -65.89887904  -58.01287126 -422.26495597  -59.28717898]
[ -58.83248335  -65.89887904  -58.01287126 -422.26495597  -59.28717898]
[ -58.90039339  -65.97388033  -58.07841754 -422.34084366  -59.36

[ -77.2169618   -86.51296612  -76.0814934  -669.04131296  -74.80590469]
[ -77.28546277  -86.58501272  -76.14556234 -669.11720066  -74.88179239]
[ -77.35514562  -86.65794572  -76.21849535 -669.19308835  -74.95768008]
[ -77.42010096  -86.7311742   -76.27813225 -669.26897605  -74.54043011]
[ -77.48269255  -86.80292533  -76.34515588 -669.34486374  -74.61631781]
[ -77.54705696  -86.8761538   -76.40922481 -669.42075144  -74.6922055 ]
[ -77.61053496  -86.94938228  -76.46945265 -669.49663913  -74.7680932 ]
[ -77.68051328  -87.02261075  -76.53352159 -669.57252683  -74.84398089]
[ -77.74960519  -87.09583922  -76.60468178 -669.64841452  -74.91986859]
[ -77.81810616  -87.16788582  -76.66875072 -669.72430222  -74.99575628]
[ -77.88010681  -87.24288711  -76.73281966 -669.80018991  -75.07164398]
[ -77.94890325  -87.31611559  -76.79541125 -669.87607761  -75.14753167]
[ -78.01444953  -87.38934406  -76.85061612 -669.9519653   -75.22341937]
[ -78.01444953  -87.38934406  -76.85061612 -669.9519653   -75.22

[ -85.73231673  -96.07605392  -84.49432061 -692.17351647  -82.19640936]
[ -85.73231673  -96.07605392  -84.49432061 -692.17351647  -82.19640936]
[ -85.73231673  -96.07605392  -84.49432061 -692.17351647  -82.19640936]
[ -85.79579473  -96.14898692  -84.55838955 -692.24940417  -82.27229706]
[ -85.86577305  -96.22191993  -84.62393583 -692.32529186  -82.34818475]
[ -85.80554521  -96.14987333  -84.55986689 -694.5209694   -82.27229706]
[ -85.86252289  -96.22310181  -84.62452677 -694.59685709  -82.34818475]
[ -85.92186432  -96.29780763  -84.69450508 -694.67274479  -82.42407245]
[ -85.92186432  -96.29780763  -84.69450508 -694.67274479  -82.42407245]
[ -85.92186432  -96.29780763  -84.69450508 -694.67274479  -82.42407245]
[ -85.98859248  -96.37014969  -84.75857402 -694.74863248  -82.49996014]
[ -86.05266142  -96.44219629  -84.82264296 -694.82452018  -82.57584784]
[ -86.11141191  -96.5151293   -84.8867119  -694.90040787  -82.65173553]
[ -86.17518538  -96.5871759   -84.95078083 -694.97629557  -82.72

[-100.28563077 -112.4001205   -98.86976836 -835.57873384  -95.10544686]
[-100.35442721 -112.4721671   -98.93383729 -835.65462153  -95.18133455]
[-100.35442721 -112.4721671   -98.93383729 -835.65462153  -95.18133455]
[-100.29242655 -112.39893862  -98.87420039 -837.85029907  -95.10544686]
[-100.36299581 -112.47187163  -98.94565605 -837.92618676  -95.18133455]
[-100.42470099 -112.5451001   -99.0067703  -838.00207446  -95.25722225]
[-100.48581524 -112.61832858  -99.07083924 -838.07796215  -95.33310994]
[-100.54988418 -112.69007971  -99.13343083 -838.15384985  -95.40899764]
[-100.60922561 -112.76419459  -99.19749977 -838.22973754  -95.48488533]
[-100.60922561 -112.76419459  -99.19749977 -838.22973754  -95.48488533]
[-100.66856705 -112.83624119  -99.2615687  -838.30562524  -95.56077303]
[-100.7391363  -112.9100606   -99.33154702 -838.38151293  -95.63666072]
[-100.80881915 -112.98299361  -99.40004799 -838.45740063  -95.71254842]
[-100.87288809 -113.05622208  -99.46411693 -838.53328832  -95.78

[-119.74544199 -134.18024932 -118.05597533 -974.48038767 -109.40223378]
[-119.74544199 -134.18024932 -118.05597533 -974.48038767 -109.40223378]
[-119.74544199 -134.18024932 -118.05597533 -974.48038767 -109.40223378]
[-119.81335202 -134.2543642  -118.12004427 -974.55627537 -109.47812147]
[-119.81335202 -134.2543642  -118.12004427 -974.55627537 -109.47812147]
[-119.81335202 -134.2543642  -118.12004427 -974.55627537 -109.47812147]
[-119.81335202 -134.2543642  -118.12004427 -974.55627537 -109.47812147]
[-119.87712549 -134.32759268 -118.18559055 -974.63216306 -109.55400917]
[-119.94651287 -134.40052568 -118.24965949 -974.70805076 -109.62989686]
[-120.0096954  -134.47227681 -118.30781905 -974.78393845 -109.70578456]
[-120.07346887 -134.54520982 -118.37188799 -974.85982615 -109.78167225]
[-120.1413789  -134.61814282 -118.43743427 -974.93571384 -109.85755995]
[-120.20515237 -134.69107583 -118.50150321 -975.01160154 -109.93344764]
[ -120.13990155  -134.61962017  -118.43891161 -1004.48231261
  -

  -117.28253883]
[ -128.7290759   -144.28105131  -126.85937319 -1071.01944688
  -117.20665114]
[ -128.66648431  -144.20989111  -126.79530425 -1075.3815027
  -117.13076344]
[ -128.73646262  -144.28282412  -126.86528257 -1075.45739039
  -117.20665114]
[ -128.79934968  -144.35487072  -126.92787416 -1075.53327809
  -117.28253883]
[ -128.8654869   -144.42750825  -126.99046576 -1075.60916578
  -117.35842653]
[ -128.93605616  -144.50073673  -127.05748938 -1075.68505348
  -117.43431422]
[ -128.93605616  -144.50073673  -127.05748938 -1075.68505348
  -117.43431422]
[ -128.99717041  -144.57278333  -127.12155832 -1075.76094117
  -117.51020192]
[ -129.05917106  -144.6460118   -127.18562726 -1075.83682887
  -117.58608961]
[ -129.05917106  -144.6460118   -127.18562726 -1075.83682887
  -117.58608961]
[ -129.1193989   -144.71924028  -127.24378682 -1075.91271656
  -117.66197731]
[ -129.18376331  -144.79217328  -127.30785575 -1075.98860426
  -117.737865  ]
[ -129.18376331  -144.79217328  -127.30785575 -1

  -131.38504395]
[ -143.30925864  -160.59061377  -141.25636519 -1142.12727034
  -131.46093164]
[ -143.37835055  -160.66266037  -141.32043413 -1142.20315803
  -131.53681934]
[ -143.37835055  -160.66266037  -141.32043413 -1142.20315803
  -131.53681934]
[ -143.44596512  -160.73588884  -141.38450307 -1142.27904573
  -131.0584073 ]
[ -143.51032952  -160.80793544  -141.45448138 -1142.35493342
  -131.13429499]
[ -143.57380752  -160.88086845  -141.51559563 -1142.43082112
  -131.21018269]
[ -143.50944312  -160.80763997  -141.45389045 -1144.51126576
  -131.13429499]
[ -143.44448777  -160.73559338  -141.39425354 -1148.87450346
  -131.0584073 ]
[ -143.50353374  -160.80704904  -141.45832248 -1148.95039115
  -131.13429499]
[ -143.57292112  -160.87998204  -141.52534611 -1149.02627885
  -131.21018269]
[ -143.57292112  -160.87998204  -141.52534611 -1149.02627885
  -131.21018269]
[ -143.6431949   -160.95291505  -141.58646035 -1149.10216654
  -131.28607038]
[ -143.70283181  -161.02525712  -141.65348398 -

[ -167.00643597  -187.25075365  -164.76178318 -1239.31525583
  -152.61234856]
[ -167.07020944  -187.32398213  -164.82585211 -1239.39114353
  -152.68823626]
[ -167.07020944  -187.32398213  -164.82585211 -1239.39114353
  -152.68823626]
[ -167.13871041  -187.3972106   -164.89139839 -1239.46703122
  -152.76412395]
[ -167.20839326  -187.47014361  -164.96285406 -1239.54291892
  -152.84001165]
[ -167.27689423  -187.54337208  -165.02987768 -1239.61880661
  -152.91589934]
[ -167.33919035  -187.61778243  -165.09394662 -1239.69469431
  -152.99178704]
[ -167.4041457   -187.69307919  -165.15801556 -1239.770582
  -153.06767473]
[ -167.4041457   -187.69307919  -165.15801556 -1239.770582
  -153.06767473]
[ -167.46703276  -187.76630766  -165.2191298  -1239.8464697
  -152.69917714]
[ -167.46703276  -187.76630766  -165.2191298  -1239.8464697
  -152.69917714]
[ -167.52696513  -187.83924067  -165.28319874 -1239.92235739
  -152.77506483]
[ -167.59251141  -187.91246914  -165.32983501 -1239.99824509
  -152.85

  -173.40642747]
[ -187.9408148   -210.57045325  -185.43614934 -1493.67128103
  -173.48231516]
[ -187.9408148   -210.57045325  -185.43614934 -1493.67128103
  -173.48231516]
[ -188.00665655  -210.64368173  -185.50021827 -1493.74716872
  -173.55820286]
[ -188.07545299  -210.71631926  -185.56428721 -1493.82305642
  -173.63409055]
[ -188.14543131  -210.78954774  -185.62835615 -1493.89894411
  -173.11874489]
[ -188.14543131  -210.78954774  -185.62835615 -1493.89894411
  -173.11874489]
[ -188.20359087  -210.86277621  -185.69478884 -1493.97483181
  -173.19463259]
[ -188.26854621  -210.93570922  -185.75885777 -1494.0507195
  -173.27052028]
[ -188.33704718  -211.01041504  -185.82292671 -1494.1266072
  -173.34640798]
[ -188.402298    -211.08364351  -185.88699565 -1494.20249489
  -173.42229567]
[ -188.46488959  -211.15598558  -185.95106459 -1494.27838259
  -173.49818337]
[ -188.46488959  -211.15598558  -185.95106459 -1494.27838259
  -173.49818337]
[ -188.53161775  -211.22803218  -186.00626945 -14

[ -210.17720732  -235.40342684  -207.34752603 -1655.54984134
  -191.5930756 ]
[ -210.24038986  -235.47665531  -207.41159497 -1655.62572904
  -191.66896329]
[ -210.30179957  -235.5516566   -207.4756639  -1655.70161673
  -191.74485099]
[ -210.37030054  -235.6237032   -207.53086877 -1655.77750443
  -191.82073868]
[ -210.44116527  -235.69781808  -207.60084709 -1655.85339212
  -191.89662638]
[ -210.44116527  -235.69781808  -207.60084709 -1655.85339212
  -191.89662638]
[ -210.50818889  -235.77075108  -207.66639337 -1655.92927982
  -191.97251407]
[ -210.4588934   -235.69899995  -207.60823381 -1661.77783989
  -191.89662638]
[ -210.52739437  -235.77222843  -207.67230275 -1661.85372758
  -191.97251407]
[ -210.59530441  -235.84486597  -207.73784903 -1661.92961528
  -192.04840177]
[ -210.6626235   -235.91809444  -207.80191797 -1662.00550297
  -192.12428946]
[ -210.6626235   -235.91809444  -207.80191797 -1662.00550297
  -192.12428946]
[ -210.72935166  -235.99014104  -207.86598691 -1662.08139067
  -

  -211.8020867 ]
[ -231.5145665   -259.25877234  -228.37109719 -1821.27253125
  -211.8779744 ]
[ -231.5145665   -259.25877234  -228.37109719 -1821.27253125
  -211.8779744 ]
[ -231.582772    -259.33081894  -228.4410755  -1821.34841895
  -211.95386209]
[ -231.65304579  -259.40404741  -228.50809913 -1821.42430664
  -212.02974979]
[ -231.72272863  -259.47727588  -228.57069072 -1821.50019434
  -212.10563748]
[ -231.78916132  -259.55020889  -228.63475966 -1821.57608203
  -212.18152518]
[ -231.78916132  -259.55020889  -228.63475966 -1821.57608203
  -212.18152518]
[ -231.85736682  -259.62225549  -228.69587391 -1821.65196973
  -212.25741287]
[ -231.92734514  -259.69518849  -228.76732957 -1821.72785742
  -212.33330057]
[ -231.99761893  -259.7681215   -228.83435319 -1821.80374512
  -212.40918826]
[ -231.99761893  -259.7681215   -228.83435319 -1821.80374512
  -212.40918826]
[ -232.06671084  -259.84105451  -228.89842213 -1821.87963281
  -212.48507596]
[ -232.13402993  -259.91428298  -228.96101372 -

[ -254.36303579  -284.75877991  -250.7778404  -2005.36874382
  -233.1793683 ]
[ -254.42710472  -284.83319026  -250.84190934 -2005.44463151
  -233.255256  ]
[ -254.42710472  -284.83319026  -250.84190934 -2005.44463151
  -233.255256  ]
[ -254.49590116  -284.90641874  -250.90597828 -2005.52051921
  -233.33114369]
[ -254.56440214  -284.97935174  -250.9682744  -2005.5964069
  -233.40703139]
[ -254.63497139  -285.05317116  -251.04179835 -2005.6722946
  -233.48291908]
[ -254.69638111  -285.12639963  -251.0999579  -2005.74818229
  -233.55880678]
[ -254.76724583  -285.19992357  -251.17082263 -2005.82406999
  -233.63469447]
[ -254.83308758  -285.27256111  -251.23341422 -2005.89995768
  -233.71058217]
[ -254.83308758  -285.27256111  -251.23341422 -2005.89995768
  -233.71058217]
[ -254.83308758  -285.27256111  -251.23341422 -2005.89995768
  -233.71058217]
[ -254.77906459  -285.19933264  -251.16934528 -2010.50163882
  -233.63469447]
[ -254.84401993  -285.27256111  -251.23341422 -2010.57752651
  -23

  -252.74993591]
[ -276.3306951   -309.40013768  -272.46096312 -2193.29008025
  -252.8258236 ]
[ -276.39624138  -309.47336616  -272.52650941 -2193.36596795
  -252.9017113 ]
[ -276.46119672  -309.54629916  -272.59057834 -2193.44185564
  -252.97759899]
[ -276.52851582  -309.61923217  -272.65316994 -2193.51774334
  -253.05348669]
[ -276.52851582  -309.61923217  -272.65316994 -2193.51774334
  -253.05348669]
[ -276.59701679  -309.69127877  -272.71132949 -2193.59363103
  -252.65957876]
[ -276.66315401  -309.76539365  -272.77539843 -2193.66951873
  -252.73546646]
[ -276.72604107  -309.83862212  -272.83946737 -2193.74540642
  -252.81135415]
[ -276.79572392  -309.9118506   -272.90353631 -2193.82129412
  -252.88724185]
[ -276.86540677  -309.98507907  -272.96760524 -2193.89718181
  -252.96312954]
[ -276.86540677  -309.98507907  -272.96760524 -2193.89718181
  -252.96312954]
[ -276.86540677  -309.98507907  -272.96760524 -2193.89718181
  -252.96312954]
[ -276.92267992  -310.05712567  -273.03167418 -

[ -298.46145326  -334.01638059  -294.22799902 -2351.13120101
  -273.15422122]
[ -298.52818142  -334.0893136   -294.2935453  -2351.2070887
  -273.23010892]
[ -298.59402317  -334.16313301  -294.35761424 -2351.2829764
  -273.30599661]
[ -298.66311508  -334.2381343   -294.42168318 -2351.35886409
  -273.38188431]
[ -298.66311508  -334.2381343   -294.42168318 -2351.35886409
  -273.38188431]
[ -298.73279793  -334.31106731  -294.4916615  -2351.43475179
  -273.457772  ]
[ -298.79686687  -334.38429578  -294.55720778 -2351.51063948
  -273.5336597 ]
[ -298.7369345   -334.31254465  -294.49313884 -2353.59108413
  -273.457772  ]
[ -298.80336718  -334.38459125  -294.55720778 -2353.66697182
  -272.94213087]
[ -298.80336718  -334.38459125  -294.55720778 -2353.66697182
  -272.94213087]
[ -298.80336718  -334.38459125  -294.55720778 -2353.66697182
  -272.94213087]
[ -298.80336718  -334.38459125  -294.55720778 -2353.66697182
  -272.94213087]
[ -298.87245909  -334.45781972  -294.62127672 -2353.74285952
  -27

  -291.63373473]
[ -321.13835074  -359.3882503   -316.51014999 -2572.97514395
  -291.70962242]
[ -321.19916952  -359.4611833   -316.57421893 -2573.05103165
  -291.78551012]
[ -321.26619315  -359.53411631  -316.63828787 -2573.12691934
  -291.86139781]
[ -321.32996662  -359.60734478  -316.70235681 -2573.20280704
  -291.93728551]
[ -321.32996662  -359.60734478  -316.70235681 -2573.20280704
  -291.93728551]
[ -321.39787665  -359.6820506   -316.76347105 -2573.27869473
  -292.0131732 ]
[ -321.33292131  -359.610004    -316.69703837 -2574.6606508
  -291.93728551]
[ -321.39699024  -359.68264154  -316.7611073  -2574.7365385
  -292.0131732 ]
[ -321.46224106  -359.75587001  -316.82517624 -2574.81242619
  -292.0890609 ]
[ -321.5271964   -359.82909849  -316.88924518 -2574.88831389
  -292.16494859]
[ -321.5271964   -359.82909849  -316.88924518 -2574.88831389
  -292.16494859]
[ -321.59126534  -359.90203149  -316.95035943 -2574.96420158
  -292.24083629]
[ -321.65681162  -359.97407809  -317.01442836 -25

[ -343.33332985  -384.32015821  -338.43713877 -2715.40854994
  -311.31304343]
[ -343.40301269  -384.39250028  -338.51036724 -2715.48443764
  -311.38893113]
[ -343.47358195  -384.46602423  -338.57679993 -2715.56032533
  -311.46481882]
[ -343.5441512   -384.54043458  -338.64323262 -2715.63621303
  -311.54070652]
[ -343.6114703   -384.61366305  -338.70730156 -2715.71210072
  -311.61659421]
[ -343.67878939  -384.68689153  -338.77137049 -2715.78798842
  -311.69248191]
[ -343.74256286  -384.76012     -338.83543943 -2715.86387611
  -311.7683696 ]
[ -343.80899555  -384.83334847  -338.89950837 -2715.93976381
  -311.8442573 ]
[ -343.86685964  -384.90746336  -338.96830481 -2716.0156515
  -311.92014499]
[ -343.91940529  -384.98069183  -339.04241969 -2716.0915392
  -311.99603269]
[ -343.98524704  -385.0530339   -339.10648863 -2716.16742689
  -312.07192038]
[ -343.98524704  -385.0530339   -339.10648863 -2716.16742689
  -312.07192038]
[ -343.98524704  -385.0530339   -339.10648863 -2716.16742689
  -31

  -329.06708168]
[ -363.66888025  -407.06289409  -358.45624193 -2903.21057845
  -329.06708168]
[ -363.7394495   -407.13612256  -358.52562931 -2903.28646615
  -329.14296938]
[ -363.80706407  -407.20816916  -358.58969825 -2903.36235384
  -328.8028368 ]
[ -363.74594982  -407.13612256  -358.52562931 -2907.72559154
  -328.72694911]
[ -363.81356438  -407.20935104  -358.58733449 -2907.80147923
  -328.8028368 ]
[ -363.88324723  -407.28228404  -358.65140343 -2907.87736693
  -328.8787245 ]
[ -363.94820257  -407.35492158  -358.71547237 -2907.95325462
  -328.95461219]
[ -364.01581714  -407.42696818  -358.77954131 -2908.02914232
  -329.03049989]
[ -364.08490905  -407.50196947  -358.84508759 -2908.10503001
  -329.10638758]
[ -364.15134174  -407.574607    -358.91063387 -2908.18091771
  -329.18227528]
[ -364.21925177  -407.64813095  -358.97174812 -2908.2568054
  -329.25816297]
[ -364.27888867  -407.72135942  -359.03581706 -2908.3326931
  -329.33405067]
[ -364.27888867  -407.72135942  -359.03581706 -29

  -344.70810029]
[ -383.07028426  -428.70513456  -377.46526319 -3043.20113099
  -344.78398799]
[ -383.13080757  -428.77895397  -377.52933213 -3043.27701868
  -344.85987568]
[ -383.19694479  -428.85188698  -377.59340106 -3043.35290638
  -344.93576338]
[ -383.26308201  -428.92511545  -377.65747    -3043.42879407
  -345.01165107]
[ -383.33158298  -428.99716205  -377.72744832 -3043.50468177
  -345.08753877]
[ -383.3891516   -429.06920865  -377.79151725 -3043.58056946
  -345.16342646]
[ -383.45381148  -429.14214166  -377.85558619 -3043.65645716
  -345.23931416]
[ -383.5161076   -429.21537013  -377.91226841 -3043.73234485
  -345.31520185]
[ -383.5161076   -429.21537013  -377.91226841 -3043.73234485
  -345.31520185]
[ -383.58076748  -429.28859861  -377.96747327 -3043.80823255
  -345.39108955]
[ -383.58076748  -429.28859861  -377.96747327 -3043.80823255
  -345.39108955]
[ -383.63804063  -429.36330443  -378.03892894 -3043.88412024
  -345.46697724]
[ -383.69945035  -429.43623743  -378.10211147 -

  -357.3864981 ]
[ -395.32852523  -442.52670171  -389.68538867 -3155.72764397
  -357.46238579]
[ -395.32852523  -442.52670171  -389.68538867 -3155.72764397
  -357.46238579]
[ -395.39288964  -442.5987483   -389.7494576  -3155.80353166
  -357.2156214 ]
[ -395.45814045  -442.67168131  -389.81352654 -3155.87941936
  -357.2915091 ]
[ -395.39909449  -442.59963471  -389.7494576  -3156.72037179
  -357.2156214 ]
[ -395.4519356   -442.67434053  -389.81500389 -3156.79625948
  -357.2915091 ]
[ -395.52073204  -442.74727354  -389.87907282 -3156.87214718
  -357.36739679]
[ -395.58509645  -442.82020654  -389.94314176 -3156.94803487
  -357.44328449]
[ -395.6547793   -442.89254861  -390.0072107  -3157.02392257
  -357.51917218]
[ -395.6547793   -442.89254861  -390.0072107  -3157.02392257
  -357.51917218]
[ -395.72416668  -442.96548162  -390.07364339 -3157.09981026
  -357.59505988]
[ -395.78941749  -443.03841462  -390.13771232 -3157.17569796
  -357.67094757]
[ -395.78941749  -443.03841462  -390.13771232 -

[ -409.8744814   -458.7373299   -403.8844643  -3205.60843549
  -373.01648199]
[ -409.94239144  -458.81174025  -403.94853324 -3205.68432318
  -373.09236969]
[ -410.01059694  -458.88555966  -404.01260217 -3205.76021088
  -373.16825738]
[ -410.08057526  -458.95849267  -404.07667111 -3205.83609857
  -373.24414508]
[ -410.08057526  -458.95849267  -404.07667111 -3205.83609857
  -373.24414508]
[ -410.14109857  -459.03172114  -404.14074005 -3205.91198627
  -373.32003277]
[ -410.20723578  -459.10494962  -404.20539992 -3205.98787396
  -373.39592047]
[ -410.27396394  -459.17699621  -404.26355948 -3206.06376166
  -373.47180816]
[ -410.34276038  -459.24992922  -404.32762842 -3206.13964935
  -373.54769586]
[ -410.40210182  -459.32197582  -404.39169736 -3206.21553705
  -373.62358355]
[ -410.40210182  -459.32197582  -404.39169736 -3206.21553705
  -373.62358355]
[ -410.40210182  -459.32197582  -404.39169736 -3206.21553705
  -373.62358355]
[ -410.46528435  -459.39490882  -404.4528116  -3206.29142474
  -

  -392.11666304]
[ -431.88828169  -483.28477637  -425.5623164  -3321.84669057
  -392.11666304]
[ -431.88828169  -483.28477637  -425.5623164  -3321.84669057
  -392.11666304]
[ -431.88828169  -483.28477637  -425.5623164  -3321.84669057
  -392.11666304]
[ -431.88828169  -483.28477637  -425.5623164  -3321.84669057
  -392.11666304]
[ -431.95028235  -483.35800484  -425.62490799 -3321.92257827
  -392.19255074]
[ -432.01641957  -483.43005144  -425.68306755 -3321.99846596
  -392.26843843]
[ -432.08255679  -483.50327992  -425.74861383 -3322.07435366
  -392.34432613]
[ -432.1525351   -483.57621292  -425.82006949 -3322.15024135
  -392.42021382]
[ -432.21630857  -483.64825952  -425.88413843 -3322.22612905
  -392.49610152]
[ -432.21630857  -483.64825952  -425.88413843 -3322.22612905
  -392.49610152]
[ -432.27624094  -483.721488    -425.94525268 -3322.30201674
  -392.57198921]
[ -432.34149176  -483.79353459  -426.00932162 -3322.37790444
  -392.64787691]
[ -432.40378788  -483.86558119  -426.07339055 -

[ -452.44440392  -506.23596985  -445.70685039 -3566.04089155
  -411.64750804]
[ -452.44440392  -506.23596985  -445.70685039 -3566.04089155
  -411.64750804]
[ -452.51260942  -506.30890285  -445.77091933 -3566.11677924
  -411.72339574]
[ -452.58140587  -506.38213133  -445.83794296 -3566.19266694
  -411.79928343]
[ -452.64754309  -506.4553598   -445.90644393 -3566.26855463
  -411.87517113]
[ -452.71663499  -506.52858828  -445.97051287 -3566.34444233
  -411.95105882]
[ -452.78188581  -506.60152128  -446.03162711 -3566.42033002
  -412.02694652]
[ -452.84684115  -506.67356788  -446.09274136 -3566.49621772
  -412.10283421]
[ -452.91563759  -506.74620542  -446.15828764 -3566.57210541
  -412.17872191]
[ -452.91563759  -506.74620542  -446.15828764 -3566.57210541
  -412.17872191]
[ -452.97675184  -506.81825202  -446.22087924 -3566.64799311
  -412.2546096 ]
[ -452.97675184  -506.81825202  -446.22087924 -3566.64799311
  -412.2546096 ]
[ -452.97675184  -506.81825202  -446.22087924 -3566.64799311
  -

  -429.74630555]
[ -474.78761279  -531.29572017  -467.8385035  -3682.13048646
  -429.74630555]
[ -474.85404548  -531.37042599  -467.90404978 -3682.20637415
  -429.82219325]
[ -474.91368238  -531.4442454   -467.96811872 -3682.28226185
  -429.89808094]
[ -474.9845471   -531.51806481  -468.03809703 -3682.35814954
  -429.97396864]
[ -475.04861604  -531.59099782  -468.10216597 -3682.43403724
  -430.04985633]
[ -475.11327592  -531.66304442  -468.16328022 -3682.50992493
  -430.12574403]
[ -475.05718464  -531.58981594  -468.09921128 -3687.11160606
  -430.04985633]
[ -475.1200717   -531.66304442  -468.16328022 -3687.18749376
  -430.12574403]
[ -475.0518662   -531.59011141  -468.09921128 -3689.38317129
  -430.04985633]
[ -475.12036717  -531.66333989  -468.16328022 -3689.45905899
  -430.12574403]
[ -475.18295876  -531.73656836  -468.22734916 -3689.53494668
  -430.20163172]
[ -475.18295876  -531.73656836  -468.22734916 -3689.53494668
  -430.20163172]
[ -475.24052738  -531.80950137  -468.28994075 -

[ -495.5243229   -554.62103368  -488.36129409 -3858.25460884
  -448.16003883]
[ -495.59046012  -554.69396669  -488.42536303 -3858.33049653
  -448.23592653]
[ -495.65630187  -554.7677861   -488.48943197 -3858.40638423
  -448.31181422]
[ -495.72628018  -554.8407191   -488.55941028 -3858.48227192
  -448.38770192]
[ -495.66132484  -554.76896797  -488.49829603 -3860.67794946
  -448.31181422]
[ -495.7203708   -554.84131004  -488.56236497 -3860.75383715
  -448.38770192]
[ -495.77941677  -554.91453852  -488.62407016 -3860.82972485
  -448.46358961]
[ -495.84909962  -554.98688058  -488.6975941  -3860.90561254
  -448.53947731]
[ -495.91316855  -555.05981359  -488.76166304 -3860.98150024
  -448.615365  ]
[ -495.98226046  -555.1327466   -488.82573197 -3861.05738793
  -448.6912527 ]
[ -496.04219284  -555.20597507  -488.89571029 -3861.13327563
  -448.76714039]
[ -496.04219284  -555.20597507  -488.89571029 -3861.13327563
  -448.76714039]
[ -495.97576015  -555.13304206  -488.83755073 -3865.49651332
  -

  -469.96808003]
[ -516.81647532  -578.4486051   -509.32813521 -4080.94016521
  -469.96808003]
[ -516.88615817  -578.52183358  -509.39368149 -4081.01605291
  -470.04396773]
[ -516.94756789  -578.59506205  -509.45775043 -4081.0919406
  -470.11985542]
[ -517.00572744  -578.66681318  -509.51886468 -4081.1678283
  -470.19574312]
[ -516.94136304  -578.59388017  -509.45775043 -4082.00878073
  -470.11985542]
[ -516.94136304  -578.59388017  -509.45775043 -4082.00878073
  -470.11985542]
[ -517.00838667  -578.66681318  -509.51945562 -4082.08466843
  -470.19574312]
[ -517.06802357  -578.74004165  -509.58352455 -4082.16055612
  -470.27163081]
[ -517.12500125  -578.81327013  -509.65350287 -4082.23644382
  -470.34751851]
[ -517.19232035  -578.8856122   -509.71757181 -4082.31233151
  -470.4234062 ]
[ -517.12825141  -578.8135656   -509.65350287 -4084.39277616
  -470.34751851]
[ -517.19172941  -578.88679407  -509.71461712 -4084.46866385
  -470.4234062 ]
[ -517.25136631  -578.96002255  -509.77868605 -40

[ -538.59547345  -602.87559589  -530.93901151 -4193.41660537
  -491.61293526]
[ -538.66101973  -602.94764249  -531.00308045 -4193.49249306
  -491.68882295]
[ -538.59724626  -602.87589136  -530.9419662  -4197.85573076
  -491.61293526]
[ -538.66338348  -602.94793796  -531.00012576 -4197.93161845
  -491.68882295]
[ -538.66338348  -602.94793796  -531.00012576 -4197.93161845
  -491.68882295]
[ -538.7295207   -603.01998456  -531.05828532 -4198.00750615
  -491.76471065]
[ -538.7295207   -603.01998456  -531.05828532 -4198.00750615
  -491.76471065]
[ -538.79743074  -603.09203115  -531.12087691 -4198.08339384
  -491.84059834]
[ -538.86681811  -603.16407775  -531.19233257 -4198.15928154
  -491.91648604]
[ -538.93502362  -603.23730623  -531.25758338 -4198.23516923
  -491.99237373]
[ -538.9920013   -603.3105347   -531.32726623 -4198.31105693
  -492.06826143]
[ -539.05370648  -603.38346771  -531.38985782 -4198.38694462
  -492.14414912]
[ -539.12279839  -603.45669618  -531.45392676 -4198.46283232
  -

  -512.64908517]
[ -560.91125153  -627.84852617  -552.89195373 -4378.23882442
  -512.72497287]
[ -560.98122984  -627.92145917  -552.95602266 -4378.31471211
  -512.80086056]
[ -560.98122984  -627.92145917  -552.95602266 -4378.31471211
  -512.80086056]
[ -561.04500331  -627.99439218  -553.01713691 -4378.39059981
  -512.87674826]
[ -561.10936772  -628.06762065  -553.08120585 -4378.4664875
  -512.47161251]
[ -561.17639134  -628.14084913  -553.14084275 -4378.5423752
  -512.54750021]
[ -561.23484637  -628.21378213  -553.20018419 -4378.61826289
  -512.6233879 ]
[ -561.30423375  -628.28582873  -553.26425312 -4378.69415059
  -512.6992756 ]
[ -561.36830269  -628.35905721  -553.33127675 -4378.77003828
  -512.77516329]
[ -561.43266709  -628.4311038   -553.392391   -4378.84592598
  -512.85105099]
[ -561.50146353  -628.50521869  -553.45114149 -4378.92181367
  -512.92693868]
[ -561.50146353  -628.50521869  -553.45114149 -4378.92181367
  -512.92693868]
[ -561.56228231  -628.57756075  -553.51521043 -43

[ -583.5033016   -653.2968745   -575.38679451 -4559.35409865
  -533.8189954 ]
[ -583.56914335  -653.36980751  -575.45086345 -4559.42998634
  -533.89488309]
[ -583.63882619  -653.44244504  -575.51788708 -4559.50587404
  -533.97077079]
[ -583.63882619  -653.44244504  -575.51788708 -4559.50587404
  -533.97077079]
[ -583.70053138  -653.51744633  -575.58195601 -4559.58176173
  -534.04665848]
[ -583.76991876  -653.59037934  -575.65193433 -4559.65764943
  -534.12254618]
[ -583.83191941  -653.66331234  -575.71009389 -4559.73353712
  -534.19843387]
[ -583.89982945  -653.73535894  -575.77416283 -4559.80942482
  -534.27432157]
[ -583.9703987   -653.80917835  -575.8426638  -4559.88531251
  -534.35020926]
[ -583.9703987   -653.80917835  -575.8426638  -4559.88531251
  -534.35020926]
[ -584.03564951  -653.88211136  -575.91264211 -4559.96120021
  -534.42609696]
[ -584.10060486  -653.95533983  -575.97671105 -4560.0370879
  -534.50198465]
[ -584.1694013   -654.02797737  -576.04668937 -4560.1129756
  -53

  -553.25422117]
[ -604.79845653  -677.04796729  -596.36047924 -4735.49713957
  -553.33010886]
[ -604.85838891  -677.12001389  -596.42218443 -4735.57302726
  -553.40599656]
[ -604.92866269  -677.19294689  -596.49364009 -4735.64891496
  -553.48188425]
[ -604.98829959  -677.2658799   -596.55859543 -4735.72480265
  -553.55777195]
[ -605.05827791  -677.3388129   -596.62621    -4735.80069035
  -553.63365964]
[ -605.11850575  -677.4108595   -596.69027893 -4735.87657804
  -553.70954734]
[ -605.11850575  -677.4108595   -596.69027893 -4735.87657804
  -553.70954734]
[ -605.18464297  -677.48408798  -596.75434787 -4735.95246574
  -553.78543503]
[ -605.24221159  -677.55702098  -596.81841681 -4736.02835343
  -553.86132273]
[ -605.31100803  -677.63024946  -596.88544044 -4736.10424113
  -553.93721042]
[ -605.38187276  -677.70465981  -596.94950937 -4736.18012882
  -554.01309812]
[ -605.45007826  -677.77759281  -597.01210097 -4736.25601652
  -554.08898581]
[ -605.51532907  -677.85082129  -597.0761699  -

[ -627.13826324  -701.90162376  -618.23905893 -4898.19503533
  -573.61315626]
[ -627.20824156  -701.97455677  -618.30962819 -4898.27092302
  -573.68904396]
[ -627.20824156  -701.97455677  -618.30962819 -4898.27092302
  -573.68904396]
[ -627.20824156  -701.97455677  -618.30962819 -4898.27092302
  -573.68904396]
[ -627.20824156  -701.97455677  -618.30962819 -4898.27092302
  -573.68904396]
[ -627.26817393  -702.04778524  -618.37369712 -4898.34681072
  -573.76493165]
[ -627.32662896  -702.12071825  -618.43717512 -4898.42269841
  -573.84081935]
[ -627.39749368  -702.19453766  -618.50774438 -4898.49858611
  -573.91670704]
[ -627.46599465  -702.26747066  -618.55999456 -4898.5744738
  -573.99259474]
[ -627.46599465  -702.26747066  -618.55999456 -4898.5744738
  -573.99259474]
[ -627.46599465  -702.26747066  -618.55999456 -4898.5744738
  -573.99259474]
[ -627.53035906  -702.34069914  -618.62406349 -4898.6503615
  -574.06848243]
[ -627.58645034  -702.41363214  -618.69522369 -4898.72624919
  -574.

  -591.33238553]
[ -647.78495097  -725.064525    -638.68098668 -5061.86730572
  -591.40827323]
[ -647.85522475  -725.13775347  -638.74357827 -5061.94319341
  -591.48416092]
[ -647.92224838  -725.21098195  -638.80912456 -5062.01908111
  -591.56004862]
[ -647.99252217  -725.28450589  -638.86964787 -5062.0949688
  -591.63593631]
[ -647.99252217  -725.28450589  -638.86964787 -5062.0949688
  -591.63593631]
[ -648.06190954  -725.35655249  -638.94258087 -5062.1708565
  -591.71182401]
[ -648.13218333  -725.42978097  -639.01019544 -5062.24674419
  -591.7877117 ]
[ -648.19477492  -725.50212303  -639.07426437 -5062.32263189
  -591.249024  ]
[ -648.26298042  -725.57535151  -639.14276534 -5062.39851958
  -591.32491169]
[ -648.19950243  -725.50123663  -639.07869641 -5091.86923066
  -591.249024  ]
[ -648.25707105  -725.5744651   -639.14424269 -5091.94511835
  -591.32491169]
[ -648.31493514  -725.64857998  -639.20831163 -5092.02100605
  -591.40079939]
[ -648.31493514  -725.64857998  -639.20831163 -509

[ -670.55118425  -750.69355686  -661.38664882 -5241.28319459
  -609.89316153]
[ -670.60963927  -750.76678533  -661.45071776 -5241.35908228
  -609.96904922]
[ -670.66898071  -750.84060475  -661.5147867  -5241.43496998
  -610.04493692]
[ -670.73511793  -750.91412869  -661.58121939 -5241.51085767
  -610.12082461]
[ -670.73511793  -750.91412869  -661.58121939 -5241.51085767
  -610.12082461]
[ -670.79800499  -750.98735716  -661.64528832 -5241.58674537
  -610.19671231]
[ -670.79800499  -750.98735716  -661.64528832 -5241.58674537
  -610.19671231]
[ -670.86473315  -751.06029017  -661.70935726 -5241.66263306
  -610.2726    ]
[ -670.9353024   -751.13410958  -661.78081292 -5241.73852076
  -610.3484877 ]
[ -670.99848493  -751.20733806  -661.83601779 -5241.81440845
  -610.42437539]
[ -671.06462215  -751.28056653  -661.90008673 -5241.89029615
  -610.50026309]
[ -671.1351914   -751.35349954  -661.9685877  -5241.96618384
  -610.57615078]
[ -671.19719206  -751.42554613  -662.03265664 -5242.04207154
  -

  -630.91935261]
[ -692.42236868  -775.10016029  -683.01229857 -5367.746839
  -630.99524031]
[ -692.48909684  -775.17545705  -683.07784485 -5367.8227267
  -631.071128  ]
[ -692.55257484  -775.24839005  -683.14250473 -5367.89861439
  -631.1470157 ]
[ -692.62078034  -775.3228004   -683.21248304 -5367.97450209
  -631.22290339]
[ -692.62078034  -775.3228004   -683.21248304 -5367.97450209
  -631.22290339]
[ -692.55316578  -775.2507538   -683.15136879 -5369.42855258
  -631.1470157 ]
[ -692.61900753  -775.32250493  -683.21543773 -5369.50444027
  -631.22290339]
[ -692.67982631  -775.39455153  -683.27950667 -5369.58032797
  -631.29879109]
[ -692.67982631  -775.39455153  -683.27950667 -5369.58032797
  -631.29879109]
[ -692.67982631  -775.39455153  -683.27950667 -5369.58032797
  -631.29879109]
[ -692.74537259  -775.46748454  -683.34357561 -5369.65621566
  -631.37467878]
[ -692.80766871  -775.54219036  -683.40764454 -5369.73210336
  -631.45056648]
[ -692.86996484  -775.61453242  -683.46698598 -536

[ -714.78039882  -800.12627498  -705.02197082 -5475.32815807
  -650.24257342]
[ -714.8506726   -800.19920798  -705.08603976 -5475.40404577
  -650.31846111]
[ -714.8506726   -800.19920798  -705.08603976 -5475.40404577
  -650.31846111]
[ -714.92124186  -800.27214099  -705.15454073 -5475.47993346
  -650.39434881]
[ -714.92124186  -800.27214099  -705.15454073 -5475.47993346
  -650.39434881]
[ -714.9900383   -800.34418759  -705.21713232 -5475.55582116
  -650.4702365 ]
[ -715.05469817  -800.41712059  -705.28090579 -5475.63170885
  -650.5461242 ]
[ -715.05469817  -800.41712059  -705.28090579 -5475.63170885
  -650.5461242 ]
[ -715.1255629   -800.49123547  -705.35088411 -5475.70759655
  -650.62201189]
[ -715.19317746  -800.56446395  -705.41495305 -5475.78348424
  -650.69789959]
[ -715.25370077  -800.63769242  -705.48847699 -5475.85937194
  -650.77378728]
[ -715.19583668  -800.56623676  -705.41849867 -5480.22260963
  -650.69789959]
[ -715.25133702  -800.64123805  -705.48256761 -5480.29849733
  -

  -668.72213475]
[ -737.24233838  -825.26604956  -727.20557864 -5669.0690115
  -668.64624705]
[ -737.24233838  -825.26604956  -727.20557864 -5669.0690115
  -668.64624705]
[ -737.18595163  -825.19400296  -727.13737313 -5670.63474925
  -668.57035936]
[ -737.24913416  -825.26811784  -727.20144207 -5670.71063695
  -668.64624705]
[ -737.24913416  -825.26811784  -727.20144207 -5670.71063695
  -668.64624705]
[ -737.31202122  -825.34105085  -727.27289773 -5670.78652464
  -668.72213475]
[ -737.37549922  -825.41221104  -727.33401198 -5670.86241234
  -668.79802244]
[ -737.37549922  -825.41221104  -727.33401198 -5670.86241234
  -668.79802244]
[ -737.37549922  -825.41221104  -727.33401198 -5670.86241234
  -668.79802244]
[ -737.37549922  -825.41221104  -727.33401198 -5670.86241234
  -668.79802244]
[ -737.37549922  -825.41221104  -727.33401198 -5670.86241234
  -668.79802244]
[ -737.44370473  -825.48425764  -727.4039903  -5670.93830003
  -668.87391014]
[ -737.51250117  -825.55630424  -727.47101392 -56

[ -758.41930574  -849.00827828  -748.07584924 -5898.86862143
  -687.41484706]
[ -758.4821928   -849.08268863  -748.13991817 -5898.94450912
  -687.49073476]
[ -758.4821928   -849.08268863  -748.13991817 -5898.94450912
  -687.49073476]
[ -758.54744361  -849.1559171   -748.20398711 -5899.02039682
  -687.56662245]
[ -758.54744361  -849.1559171   -748.20398711 -5899.02039682
  -687.56662245]
[ -758.49135234  -849.08268863  -748.13696348 -5904.86895689
  -687.49073476]
[ -758.55867143  -849.15473523  -748.20103242 -5904.94484458
  -687.56662245]
[ -758.61919474  -849.2279637   -748.26510136 -5905.02073228
  -687.64251015]
[ -758.68415009  -849.30119218  -748.3291703  -5905.09661997
  -687.23737441]
[ -758.75383293  -849.37412518  -748.39323923 -5905.17250767
  -687.3132621 ]
[ -758.81908375  -849.44705819  -748.45789911 -5905.24839536
  -687.3891498 ]
[ -758.88788019  -849.52028666  -748.52492274 -5905.32428306
  -687.46503749]
[ -758.95460835  -849.59351514  -748.58899167 -5905.40017075
  -

  -706.37073509]
[ -780.18003261  -873.35554028  -769.55381233 -6078.02654032
  -706.44662279]
[ -780.24026045  -873.42876875  -769.61788127 -6078.10242802
  -706.52251048]
[ -780.31053424  -873.50170176  -769.68638224 -6078.17831571
  -706.59839818]
[ -780.31053424  -873.50170176  -769.68638224 -6078.17831571
  -706.59839818]
[ -780.31053424  -873.50170176  -769.68638224 -6078.17831571
  -706.59839818]
[ -780.37135302  -873.57670304  -769.75045118 -6078.25420341
  -706.67428587]
[ -780.42892164  -873.64963605  -769.81452012 -6078.3300911
  -706.75017357]
[ -780.42892164  -873.64963605  -769.81452012 -6078.3300911
  -706.75017357]
[ -780.4965362   -873.72286452  -769.87711171 -6078.4059788
  -706.82606126]
[ -780.4965362   -873.72286452  -769.87711171 -6078.4059788
  -706.82606126]
[ -780.55410482  -873.79491112  -769.94118065 -6078.48186649
  -706.90194896]
[ -780.61315079  -873.8681396   -770.00820427 -6078.55775419
  -706.97783665]
[ -780.61315079  -873.8681396   -770.00820427 -6078

[ -802.43233269  -898.26942459  -791.52305317 -6243.78662838
  -726.72489486]
[ -802.49521975  -898.34147119  -791.5871221  -6243.86251607
  -726.80078256]
[ -802.43440097  -898.26942459  -791.51714379 -6246.05819361
  -726.72489486]
[ -802.49846991  -898.34235759  -791.58180366 -6246.1340813
  -726.80078256]
[ -802.5687437   -898.41558607  -791.6458726  -6246.209969
  -726.87667025]
[ -802.62867607  -898.48851907  -791.70994154 -6246.28585669
  -726.95255795]
[ -802.68831297  -898.56174755  -791.77401047 -6246.36174439
  -727.02844564]
[ -802.74735894  -898.63438508  -791.83807941 -6246.43763208
  -727.10433334]
[ -802.81467803  -898.70731809  -791.90510304 -6246.51351978
  -727.18022103]
[ -802.87549681  -898.78054656  -791.96828557 -6246.58940747
  -727.25610873]
[ -802.93838387  -898.85377504  -792.03324091 -6246.66529517
  -727.33199642]
[ -803.00393016  -898.92641258  -792.09671891 -6246.74118286
  -727.40788412]
[ -803.06799909  -898.99964105  -792.16078785 -6246.81707056
  -727

  -747.06725293]
[ -825.4277064   -924.13557454  -814.30893939 -6417.38665859
  -747.06725293]
[ -825.36216012  -924.06234606  -814.24487045 -6418.72518072
  -746.99136524]
[ -825.42504718  -924.13557454  -814.30066626 -6418.80106841
  -747.06725293]
[ -825.42504718  -924.13557454  -814.30066626 -6418.80106841
  -747.06725293]
[ -825.49029799  -924.20762114  -814.3647352  -6418.87695611
  -747.14314063]
[ -825.55850349  -924.27966773  -814.42732679 -6418.9528438
  -747.21902832]
[ -825.55850349  -924.27966773  -814.42732679 -6418.9528438
  -747.21902832]
[ -825.62818634  -924.35289621  -814.49494136 -6419.0287315
  -747.29491602]
[ -825.56382193  -924.28144055  -814.43087242 -6421.22440903
  -747.21902832]
[ -825.49916206  -924.20880301  -814.36680348 -6425.38672785
  -747.14314063]
[ -825.49916206  -924.20880301  -814.36680348 -6425.38672785
  -747.14314063]
[ -825.49916206  -924.20880301  -814.36680348 -6425.38672785
  -747.14314063]
[ -825.56766303  -924.28321336  -814.43087242 -642

[ -845.69288737  -946.96572139  -834.41752182 -6573.99421021
  -764.53463849]
[ -845.75518349  -947.03924534  -834.48011341 -6574.0700979
  -764.61052618]
[ -845.8204343   -947.11365569  -834.54418235 -6574.1459856
  -764.68641388]
[ -845.8204343   -947.11365569  -834.54418235 -6574.1459856
  -764.68641388]
[ -845.88863981  -947.18688416  -834.60825129 -6574.22187329
  -764.76230157]
[ -845.82988931  -947.11424663  -834.54418235 -6578.58511099
  -764.68641388]
[ -845.82988931  -947.11424663  -834.54418235 -6578.58511099
  -764.68641388]
[ -845.89661747  -947.18629323  -834.60825129 -6578.66099868
  -764.76230157]
[ -845.96511844  -947.2595217   -834.67232022 -6578.73688638
  -764.83818927]
[ -846.02977831  -947.3315683   -834.73166166 -6578.81277407
  -764.91407696]
[ -846.09591553  -947.4036149   -834.7957306  -6578.88866177
  -764.98996466]
[ -846.15673431  -947.4765479   -834.85979953 -6578.96454946
  -765.06585235]
[ -846.22671263  -947.54918544  -834.92386847 -6579.04043716
  -765

  -782.63733344]
[ -868.32575997  -972.32311312  -856.77797206 -6725.82412804
  -782.56144575]
[ -868.32575997  -972.32311312  -856.77797206 -6725.82412804
  -782.56144575]
[ -868.32575997  -972.32311312  -856.77797206 -6725.82412804
  -782.56144575]
[ -868.32575997  -972.32311312  -856.77797206 -6725.82412804
  -782.56144575]
[ -868.38628328  -972.39515972  -856.83613162 -6725.90001573
  -782.63733344]
[ -868.38628328  -972.39515972  -856.83613162 -6725.90001573
  -782.63733344]
[ -868.45448878  -972.46838819  -856.90020056 -6725.97590343
  -782.71322114]
[ -868.51412569  -972.54043479  -856.96426949 -6726.05179112
  -782.78910883]
[ -868.58499041  -972.61454967  -857.03602062 -6726.12767882
  -782.86499653]
[ -868.65290044  -972.68748268  -857.10008956 -6726.20356651
  -782.94088422]
[ -868.59799104  -972.61454967  -857.03897531 -6732.05212658
  -782.86499653]
[ -868.66353733  -972.68659627  -857.10008956 -6732.12801427
  -782.94088422]
[ -868.73440205  -972.76071115  -857.17124975 -

[ -889.77185172  -996.14300235  -877.76431413 -6872.70535443
  -801.48600554]
[ -889.83532972  -996.21504895  -877.82838307 -6872.78124212
  -801.56189323]
[ -889.89998959  -996.28768648  -877.8954067  -6872.85712982
  -801.63778093]
[ -889.96139931  -996.36327871  -877.95947563 -6872.93301751
  -801.71366862]
[ -889.96139931  -996.36327871  -877.95947563 -6872.93301751
  -801.71366862]
[ -889.96139931  -996.36327871  -877.95947563 -6872.93301751
  -801.71366862]
[ -890.02517278  -996.43650718  -878.02354457 -6873.00890521
  -801.35078494]
[ -890.09367375  -996.50973566  -878.08761351 -6873.0847929
  -801.42667264]
[ -890.16276566  -996.58178226  -878.15168245 -6873.1606806
  -801.50256033]
[ -890.16276566  -996.58178226  -878.15168245 -6873.1606806
  -801.50256033]
[ -890.23363038  -996.65589714  -878.22018342 -6873.23656829
  -801.57844803]
[ -890.29622197  -996.72794374  -878.28425235 -6873.31245599
  -801.65433572]
[ -890.29622197  -996.72794374  -878.28425235 -6873.31245599
  -801

  -824.63281987]
[ -913.56953631 -1022.74646001  -901.1959127  -6973.33855561
  -824.70870757]
[ -913.63981009 -1022.81939302  -901.26441367 -6973.41444331
  -824.78459526]
[ -913.708902   -1022.89262149  -901.3314373  -6973.490331
  -824.86048296]
[ -913.708902   -1022.89262149  -901.3314373  -6973.490331
  -824.86048296]
[ -913.64631041 -1022.82087036  -901.27032305 -6975.68600853
  -824.78459526]
[ -913.71717513 -1022.89439431  -901.34148324 -6975.76189623
  -824.86048296]
[ -913.7856761  -1022.96762278  -901.40318843 -6975.83778392
  -824.93637065]
[ -913.85535895 -1023.04055579  -901.46725737 -6975.91367162
  -825.01225835]
[ -913.85535895 -1023.04055579  -901.46725737 -6975.91367162
  -825.01225835]
[ -913.92622367 -1023.11467067  -901.53723568 -6975.98955931
  -825.08814604]
[ -913.98349683 -1023.18789914  -901.60130462 -6976.06544701
  -825.16403374]
[ -914.05022498 -1023.25965027  -901.66448715 -6976.1413347
  -825.23992143]
[ -914.11281658 -1023.33287875  -901.72855609 -6976.

[ -934.08577023 -1045.69528974  -921.43588316 -7215.27478293
  -843.71923176]
[ -934.1533848  -1045.76851821  -921.4999521  -7215.35067062
  -843.79511946]
[ -934.21715826 -1045.84056481  -921.56254369 -7215.42655832
  -843.87100715]
[ -934.2812272  -1045.91379329  -921.63399936 -7215.50244601
  -843.94689485]
[ -934.34677348 -1045.9876127   -921.69806829 -7215.57833371
  -844.02278254]
[ -934.41054695 -1046.06202305  -921.75327316 -7215.6542214
  -844.09867024]
[ -934.47816152 -1046.13525153  -921.81881944 -7215.7301091
  -844.17455793]
[ -934.53838936 -1046.20848     -921.88288838 -7215.80599679
  -844.25044563]
[ -934.60659486 -1046.28141301  -921.94547997 -7215.88188449
  -844.32633332]
[ -934.67420942 -1046.35464148  -922.00954891 -7215.95777218
  -844.40222102]
[ -934.74211946 -1046.42757449  -922.07361785 -7216.03365988
  -844.47810871]
[ -934.81002949 -1046.50080296  -922.14714179 -7216.10954757
  -844.55399641]
[ -934.81002949 -1046.50080296  -922.14714179 -7216.10954757
  -84

  -866.12519275]
[ -957.20819558 -1071.5841908   -944.3225243  -7349.67583496
  -866.20108044]
[ -957.27787843 -1071.65771474  -944.38659324 -7349.75172265
  -866.27696814]
[ -957.34697034 -1071.73035228  -944.45184405 -7349.82761035
  -866.35285583]
[ -957.41694865 -1071.80328528  -944.52536799 -7349.90349804
  -866.42874353]
[ -957.41694865 -1071.80328528  -944.52536799 -7349.90349804
  -866.42874353]
[ -957.47540368 -1071.87651376  -944.58648224 -7349.97938574
  -866.50463122]
[ -957.41665319 -1071.80476263  -944.5224133  -7354.34262343
  -866.42874353]
[ -957.41665319 -1071.80476263  -944.5224133  -7354.34262343
  -866.42874353]
[ -957.41665319 -1071.80476263  -944.5224133  -7354.34262343
  -866.42874353]
[ -957.48397228 -1071.87769563  -944.58648224 -7354.41851113
  -866.50463122]
[ -957.55040497 -1071.94974223  -944.65055118 -7354.49439882
  -866.58051892]
[ -957.55040497 -1071.94974223  -944.65055118 -7354.49439882
  -866.58051892]
[ -957.60945093 -1072.02297071  -944.71314277 -

[ -978.45878253 -1095.26707808  -965.2073207  -7529.29393394
  -887.2442482 ]
[ -978.52964726 -1095.3408975   -965.27138964 -7529.36982163
  -887.32013589]
[ -978.52964726 -1095.3408975   -965.27138964 -7529.36982163
  -887.32013589]
[ -978.59223885 -1095.4138305   -965.31802591 -7529.44570933
  -887.39602359]
[ -978.65512591 -1095.4858771   -965.38209484 -7529.52159702
  -887.47191128]
[ -978.72303594 -1095.55851464  -965.44616378 -7529.59748472
  -887.54779898]
[ -978.78385472 -1095.63292499  -965.51023272 -7529.67337241
  -887.62368667]
[ -978.84526444 -1095.70615346  -965.57282431 -7529.74926011
  -887.69957437]
[ -978.84526444 -1095.70615346  -965.57282431 -7529.74926011
  -887.69957437]
[ -978.90519681 -1095.78085928  -965.6354159  -7529.8251478
  -887.77546206]
[ -978.96837934 -1095.85408776  -965.69948484 -7529.9010355
  -887.85134976]
[ -979.03481203 -1095.92731623  -965.76503112 -7529.97692319
  -887.92723745]
[ -978.96956122 -1095.85497416  -965.70184859 -7533.00936877
  -88

  -903.48367   ]
[ -996.73103066 -1115.83452895  -983.31853825 -7864.62474461
  -903.48367   ]
[ -996.79923616 -1115.90834837  -983.38851657 -7864.7006323
  -903.5595577 ]
[ -996.86891901 -1115.98157684  -983.45258551 -7864.77652
  -903.63544539]
[ -996.93978373 -1116.05569172  -983.52404117 -7864.85240769
  -903.71133309]
[ -997.00651189 -1116.1289202   -983.5881101  -7864.92829539
  -903.78722078]
[ -997.06733067 -1116.20126226  -983.65513373 -7865.00418308
  -903.86310848]
[ -997.06733067 -1116.20126226  -983.65513373 -7865.00418308
  -903.86310848]
[ -997.06733067 -1116.20126226  -983.65513373 -7865.00418308
  -903.86310848]
[ -997.06733067 -1116.20126226  -983.65513373 -7865.00418308
  -903.86310848]
[ -997.06733067 -1116.20126226  -983.65513373 -7865.00418308
  -903.86310848]
[ -997.06733067 -1116.20126226  -983.65513373 -7865.00418308
  -903.86310848]
[ -997.13494523 -1116.27330886  -983.71920267 -7865.08007078
  -903.93899617]
[ -997.19901417 -1116.34505999  -983.78327161 -7865

[-1019.03656297 -1140.69291293 -1005.29225894 -8071.74491851
  -923.15539216]
[-1019.10122285 -1140.76584593 -1005.35691882 -8071.82080621
  -923.23127985]
[-1019.10122285 -1140.76584593 -1005.35691882 -8071.82080621
  -923.23127985]
[-1019.16470084 -1140.83789253 -1005.42926088 -8071.8966939
  -923.30716755]
[-1019.23113353 -1140.91200741 -1005.49332982 -8071.9725816
  -923.38305524]
[-1019.23113353 -1140.91200741 -1005.49332982 -8071.9725816
  -923.38305524]
[-1019.28840669 -1140.98494042 -1005.56035345 -8072.04846929
  -923.45894294]
[-1019.35808953 -1141.05935077 -1005.62205863 -8072.12435699
  -923.53483063]
[-1019.35808953 -1141.05935077 -1005.62205863 -8072.12435699
  -923.53483063]
[-1019.42127206 -1141.13228377 -1005.68612757 -8072.20024468
  -923.61071833]
[-1019.48681834 -1141.20551225 -1005.74428713 -8072.27613238
  -923.68660602]
[-1019.55177369 -1141.2799226  -1005.80835607 -8072.35202007
  -923.76249372]
[-1019.61259247 -1141.35315107 -1005.87094766 -8072.42790777
  -923

  -943.86159891]
[-1041.2144527  -1165.55395612 -1027.17261144 -8259.94267041
  -943.9374866 ]
[-1041.2144527  -1165.55395612 -1027.17261144 -8259.94267041
  -943.9374866 ]
[-1041.2788171  -1165.6271846  -1027.23668038 -8260.0185581
  -944.0133743 ]
[-1041.33934041 -1165.69982213 -1027.30074932 -8260.0944458
  -944.08926199]
[-1041.33934041 -1165.69982213 -1027.30074932 -8260.0944458
  -944.08926199]
[-1041.39779544 -1165.77245967 -1027.36481826 -8260.17033349
  -944.16514969]
[-1041.39779544 -1165.77245967 -1027.36481826 -8260.17033349
  -944.16514969]
[-1041.39779544 -1165.77245967 -1027.36481826 -8260.17033349
  -944.16514969]
[-1041.39779544 -1165.77245967 -1027.36481826 -8260.17033349
  -944.16514969]
[-1041.39779544 -1165.77245967 -1027.36481826 -8260.17033349
  -944.16514969]
[-1041.45772781 -1165.8442108  -1027.42888719 -8260.24622119
  -944.24103738]
[-1041.52711519 -1165.91743927 -1027.49738817 -8260.32210888
  -944.31692508]
[-1041.46600094 -1165.8442108  -1027.43331923 -826

[-1061.74807147 -1188.59758356 -1047.49526539 -8462.12616292
  -960.89770398]
[-1061.74807147 -1188.59758356 -1047.49526539 -8462.12616292
  -960.89770398]
[-1061.81036759 -1188.67199391 -1047.55933432 -8462.20205062
  -960.97359168]
[-1061.87059543 -1188.74492691 -1047.6192667  -8462.27793831
  -961.04947937]
[-1061.94027828 -1188.81726898 -1047.69072236 -8462.35382601
  -961.12536707]
[-1062.00198346 -1188.89049745 -1047.75183661 -8462.4297137
  -961.20125476]
[-1061.93968734 -1188.81726898 -1047.6913133  -8463.27066614
  -961.12536707]
[-1062.00671097 -1188.89049745 -1047.75390489 -8463.34655383
  -961.20125476]
[-1062.07550741 -1188.96372593 -1047.81797383 -8463.42244153
  -961.27714246]
[-1062.1419401  -1189.03784081 -1047.87908807 -8463.49832922
  -961.35303015]
[-1062.20896372 -1189.11106928 -1047.94315701 -8463.57421692
  -961.42891785]
[-1062.26800969 -1189.18222948 -1048.00427126 -8463.65010461
  -961.50480554]
[-1062.32735112 -1189.25693529 -1048.0683402  -8463.72599231
  -9

In [5]:
#PLotting the two regressions
# x = np.linspace(0, maxcycle, 1000)
# fig, ax = plt.subplots()
# ax.plot(x, like)
# ax.plot(x, like_l2)
# plt.title('Logistic Regression Likelihood over iterations')
# plt.legend()
# plt.xlabel('Max cycles')
# plt.ylabel('Likelihood')
# plt.tight_layout()